# Form implementation generated from reading ui file 'IA2_main_window.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


import sys
from PyQt6 import QtCore, QtGui, QtWidgets
from help_window import Ui_HelpWindow
from login_window import Ui_LoginWindow
from statistics_window import Ui_StatsWindow
from create_account import Ui_create_userWindow
import main_running_window




class Ui_Main_menuWindow(object):
    def __init__(self):
            self.difficulty = "easy"
            self.pack_size = 20

    def openHelpWindow(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_HelpWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def openLoginWindow(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_LoginWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def openStatsWindow(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_StatsWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def openCreateAccountWindow(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_create_userWindow()
        self.ui.setupUi(self.window)
        self.window.show()



    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1244, 604)
        MainWindow.setStyleSheet("\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 0, 197, 255), stop:1 rgba(0, 255, 255, 255));")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.title_lb = QtWidgets.QLabel(self.centralwidget)
        self.title_lb.setStyleSheet("color: rgb(255, 255, 255);\n"
"\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0.532, y2:0.102273, stop:1 rgba(0, 0, 0, 0));\n"
"font: 87 8pt \"Bodoni MT Black\";\n"
"")
        self.title_lb.setObjectName("title_lb")
        self.gridLayout.addWidget(self.title_lb, 0, 0, 1, 3)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setStyleSheet("\n"
"background-color: rgb(0, 0, 0);")
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 1, 0, 1, 3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.login_btn = QtWidgets.QPushButton(self.centralwidget)
        self.login_btn.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0.04, x2:1, y2:1, stop:0 rgba(52, 110, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 36pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.login_btn.setObjectName("login_btn")
        self.horizontalLayout.addWidget(self.login_btn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.create_account_btn = QtWidgets.QPushButton(self.centralwidget)
        self.create_account_btn.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.502, y1:0, x2:0.507463, y2:1, stop:0 rgba(52, 110, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 36pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.create_account_btn.setObjectName("create_account_btn")
        self.horizontalLayout.addWidget(self.create_account_btn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.view_stats_btn = QtWidgets.QPushButton(self.centralwidget)
        self.view_stats_btn.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:0.0740909, x2:0, y2:1, stop:0 rgba(52, 110, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 36pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.view_stats_btn.setObjectName("view_stats_btn")
        self.horizontalLayout.addWidget(self.view_stats_btn)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 3)
        spacerItem2 = QtWidgets.QSpacerItem(20, 65, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem2, 3, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.choose_dif_lb = QtWidgets.QLabel(self.centralwidget)
        self.choose_dif_lb.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0, stop:0 rgba(0, 0, 197, 255), stop:1 rgba(0, 255, 255, 255));\n"
"color: rgb(255, 255, 255);")
        self.choose_dif_lb.setObjectName("choose_dif_lb")
        self.verticalLayout.addWidget(self.choose_dif_lb)
        self.easy_btn = QtWidgets.QPushButton(self.centralwidget)
        self.easy_btn.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(52, 110, 255, 255), stop:1 rgba(0, 255, 0, 255));\n"
"color: rgb(255, 255, 255);\n"
"font: 28pt \"MS Shell Dlg 2\";")
        self.easy_btn.setObjectName("easy_btn")
        self.verticalLayout.addWidget(self.easy_btn)
        self.medium_btn = QtWidgets.QPushButton(self.centralwidget)
        self.medium_btn.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(52, 110, 255, 255), stop:1 rgba(255, 85, 0, 255));\n"
"color: rgb(255, 255, 255);\n"
"font: 28pt \"MS Shell Dlg 2\";\n"
"")
        self.medium_btn.setObjectName("medium_btn")
        self.verticalLayout.addWidget(self.medium_btn)
        self.hard_btn = QtWidgets.QPushButton(self.centralwidget)
        self.hard_btn.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(52, 110, 255, 255), stop:1 rgba(255, 0, 0, 255));\n"
"color: rgb(255, 255, 255);\n"
"font: 28pt \"MS Shell Dlg 2\";")
        self.hard_btn.setObjectName("hard_btn")
        self.verticalLayout.addWidget(self.hard_btn)
        self.gridLayout.addLayout(self.verticalLayout, 4, 0, 3, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.packsize_lb = QtWidgets.QLabel(self.centralwidget)
        self.packsize_lb.setStyleSheet("background-color: rgb(97, 154, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.packsize_lb.setObjectName("packsize_lb")
        self.horizontalLayout_2.addWidget(self.packsize_lb)
        self.pack_size_line_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.pack_size_line_edit.setStyleSheet("background-color: rgb(97, 154, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.pack_size_line_edit.setObjectName("pack_size_line_edit")
        self.horizontalLayout_2.addWidget(self.pack_size_line_edit)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.help_btn = QtWidgets.QPushButton(self.centralwidget)
        self.help_btn.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0, stop:0 rgba(0, 0, 197, 255), stop:1 rgba(0, 255, 255, 255));\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.help_btn.setObjectName("help_btn")
        self.horizontalLayout_2.addWidget(self.help_btn)
        self.gridLayout.addLayout(self.horizontalLayout_2, 4, 1, 1, 2)
        spacerItem5 = QtWidgets.QSpacerItem(20, 65, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem5, 5, 2, 1, 1)
        self.play_game_btn = QtWidgets.QPushButton(self.centralwidget)
        self.play_game_btn.setStyleSheet("font: 72pt \"MS Shell Dlg 2\";\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0, stop:0 rgba(0, 0, 197, 255), stop:1 rgba(0, 255, 255, 255));\n"
"color: rgb(255, 255, 255);")
        self.play_game_btn.setObjectName("play_game_btn")
        self.gridLayout.addWidget(self.play_game_btn, 6, 1, 1, 2)
        spacerItem6 = QtWidgets.QSpacerItem(20, 65, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem6, 7, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def diffeasy(self):
        self.difficulty = "easy"
        
    def diffmed(self):
        self.difficulty = "med"

    def diffhard(self):
        self.difficulty = "hard"


    def rungamewin(self):
        if hasattr(self, 'ui'):
            self.pack_size = self.pack_size_line_edit.text()
        main_window = main_running_window.MainWindow(self.difficulty, self.pack_size)
        main_window.show()
        MainWindow.close()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title_lb.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:26pt;\">ULTRA SUPER MEGA CARDS: TOP TRUMPS GAME</span></p></body></html>"))
        self.login_btn.setText(_translate("MainWindow", "Login"))
        self.create_account_btn.setText(_translate("MainWindow", "Create Account"))
        self.view_stats_btn.setText(_translate("MainWindow", "View Stats"))
        self.choose_dif_lb.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Choose Difficulty:</p></body></html>"))
        self.easy_btn.setText(_translate("MainWindow", "Easy"))
        self.medium_btn.setText(_translate("MainWindow", "Medium"))
        self.hard_btn.setText(_translate("MainWindow", "Hard"))
        self.packsize_lb.setText(_translate("MainWindow", "select pack size:"))
        self.pack_size_line_edit.setText(_translate("MainWindow", "{5-50}"))
        self.help_btn.setText(_translate("MainWindow", "help"))
        self.play_game_btn.setText(_translate("MainWindow", "PLAY GAME"))
        self.create_account_btn.clicked.connect(self.openCreateAccountWindow)
        self.login_btn.clicked.connect(self.openLoginWindow)
        self.help_btn.clicked.connect(self.openHelpWindow)
        self.view_stats_btn.clicked.connect(self.openStatsWindow)
        self.easy_btn.clicked.connect(self.diffeasy)
        self.medium_btn.clicked.connect(self.diffmed)
        self.hard_btn.clicked.connect(self.diffhard)
        self.play_game_btn.clicked.connect(self.rungamewin)

        

if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_Main_menuWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())